# Generated by Django 5.0.1 on 2024-01-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_add', models.CharField(max_length=100)),
                ('cust_email', models.CharField(max_length=100)),
                ('cust_pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('med_category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('phar_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_add', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('purchase_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('med_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('total_amount', models.BigIntegerField()),
                ('cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('med_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.medicines')),
                ('phar_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.pharmacy')),
                ('purchase_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchasing')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('purchase_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.purchasing')),
                ('sales_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sales')),
            ],
        ),
    ]
